export enum NomProfile {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN_PORT = 'ADMIN_PORT',
  RESPONSABLE_PREVISION = 'RESPONSABLE_PREVISION',
  RESPONSABLE_REALISATION = 'RESPONSABLE_REALISATION',
  RESPONSABLE_VALIDATION = 'RESPONSABLE_VALIDATION', // Fixed typo
  CONSULTANT_COMPTES = 'CONSULTANT_COMPTES',
}
